### ISSUE TITLE
Accounts blocked after few hours

### ISSUE THREAD

**Issue by Frogleim** [ALIILAPRO/spotify-account-creator#10]
Hi! 
I have used your app, and after few hours spotify blocked accounts wich I have created, could you please tell me how can escape it?

**Comment by maximilianosinski** [comment]
### I've programmed Spotify bots many times, so I know what I'm saying.
**The accounts are deleted because cookies and reCAPTCHA tokens are missing when registering**, when registering in the browser the accounts are not deleted because the request to the API includes cookies and a verified reCAPTCHA token. 
**This means that there is not much you can do about it at the moment**.
### I'm currently working on a bot that automates all this.

_* You can reduce the chance of account deletion by changing and confirming the email address of the accounts. I have already programmed a bot for this purpose._

`my discord: nightteen#0510`
